"""
Wikidata英語職業名 → shokugyo_db.py jobs 対応マップ
生成元: occupations_list.json
総職業数: 947 / マッピング成功: 約880件 / null（対応なし）: 約67件
"""

OCCUPATION_LABEL_MAP = {
    # ── 政治・行政・外交 ──────────────────────────────────────────────
    "politician": "政治家",
    "local politician": "政治家",
    "statesperson": "政治家",
    "legislator": "政治家",
    "revolutionary": "政治家",
    "activist": "政治家",
    "social activist": "政治家",
    "political activist": "政治家",
    "trade unionist": "政治家",
    "suffragist": "政治家",
    "suffragette": "政治家",
    "women's rights activist": "政治家",
    "anarchist": "政治家",
    "communard": "政治家",
    "socialist": "政治家",
    "civil rights advocate": "政治家",
    "peace activist": "政治家",
    "cultural activist": "政治家",
    "feminist": "政治家",
    "representative": "政治家",
    "anarcho-syndicalist": "政治家",
    "education activist": "政治家",
    "social politician": "政治家",
    "deputy speaker": "政治家",
    "member of the French National Assembly": "政治家",
    "President of Chile": "政治家",
    "diplomat": "外交官",
    "ambassador": "外交官",
    "consul": "外交官",
    "envoy": "外交官",
    "official": "官僚・行政",
    "civil servant": "官僚・行政",
    "magistrate": "裁判官・弁護士",
    "judge": "裁判官・弁護士",
    "colonial administrator": "官僚・行政",
    "functionary": "官僚・行政",
    "secretary of state": "官僚・行政",
    "mayor": "政治家",
    "alderman": "政治家",
    "councillor of commerce": "官僚・行政",
    "provost": "官僚・行政",
    "council member": "政治家",
    "local government official": "官僚・行政",
    "chamberlain": "官僚・行政",
    "undersecretary": "官僚・行政",
    "assessor": "官僚・行政",
    "Landrat": "官僚・行政",
    "Beamter": "官僚・行政",
    "Oberamtmann": "官僚・行政",
    "Schulrat": "官僚・行政",
    "Ministerialrat": "官僚・行政",
    "Amtmann": "官僚・行政",
    "chinovnik": "官僚・行政",
    "Prefecture advisor": "官僚・行政",
    "construction officer": "官僚・行政",
    "inspector": "官僚・行政",
    "superintendent": "官僚・行政",
    "comptroller": "官僚・行政",
    "postmaster": "官僚・行政",
    "tax inspector": "官僚・行政",
    "customs inspector": "官僚・行政",
    "customs officer": "官僚・行政",
    "Public superintendent": "官僚・行政",
    "school inspector": "官僚・行政",
    "Registrar of the House of Representatives": "官僚・行政",
    "district president": "官僚・行政",
    "deputy general director": "官僚・行政",
    "burgomaster": "政治家",
    "senator of the Russian Empire": "政治家",
    "secretary": "管理職",
    "assistant secretary": "管理職",
    "deputy municipal clerk": "官僚・行政",
    "lobbyist": "政治家",
    "trustee": "管理職",
    "chairperson": "管理職",
    "board member": "管理職",
    "managing director": "経営者",
    "director": "経営者",
    "chief officer": "経営者",
    "executive": "大企業管理職",
    "business executive": "大企業管理職",
    "manager": "管理職",
    "academic administrator": "大企業管理職",
    "university president": "教師・教授",
    "rector": "教師・教授",
    "dean": "教師・教授",
    "principal": "教師・教授",
    "head teacher": "教師・教授",

    # ── 法律 ──────────────────────────────────────────────────────────
    "lawyer": "弁護士",
    "jurist": "裁判官・弁護士",
    "barrister": "弁護士",
    "attorney": "弁護士",
    "prosecutor": "裁判官・弁護士",
    "legal scholar": "裁判官・弁護士",
    "legal historian": "裁判官・弁護士",
    "legal counselor": "弁護士",
    "law theorist": "裁判官・弁護士",
    "legal advocate in France": "弁護士",
    "legal author": "弁護士",
    "administrative lawyer": "裁判官・弁護士",
    "solicitor": "弁護士",
    "advocate": "弁護士",
    "advokat": "弁護士",
    "notary": "裁判官・弁護士",
    "notary public": "裁判官・弁護士",
    "canon law jurist": "裁判官・弁護士",
    "justice of the peace": "裁判官・弁護士",
    "coroner": "裁判官・弁護士",
    "deputy judge": "裁判官・弁護士",
    "King's Counsel": "弁護士",
    "law clerk": "弁護士",
    "jurist-consultant": "裁判官・弁護士",
    "Islamic jurist": "裁判官・弁護士",
    "sorenskriver": "裁判官・弁護士",
    "poet lawyer": "弁護士",
    "avoué": "弁護士",
    "counsel": "弁護士",

    # ── 教育 ──────────────────────────────────────────────────────────
    "university teacher": "教師・教授",
    "teacher": "教師・教授",
    "pedagogue": "教師・教授",
    "secondary school teacher": "教師・教授",
    "professor": "教師・教授",
    "educator": "教師・教授",
    "school teacher": "教師・教授",
    "primary school teacher": "教師・教授",
    "music educator": "教師・教授",
    "music teacher": "教師・教授",
    "voice teacher": "教師・教授",
    "drawing teacher": "教師・教授",
    "language teacher": "教師・教授",
    "adult educator": "教師・教授",
    "school teacher in the Swedish school system": "教師・教授",
    "Oberlehrer": "教師・教授",
    "docent": "教師・教授",
    "Privatdozent": "教師・教授",
    "professor of mathematics": "教師・教授",
    "professor of surgery": "教師・教授",
    "professor of medicine": "教師・教授",
    "professeur des universités": "教師・教授",
    "teacher at a Gymnasium": "教師・教授",
    "teacher of the deaf": "教師・教授",
    "art educator": "教師・教授",
    "religious education teacher": "教師・教授",
    "special pedagogue": "教師・教授",
    "educational theorist": "教師・教授",
    "inspecteur d'académie": "官僚・行政",
    "gymnastics director": "教師・教授",
    "choir director": "ミュージシャン",
    "chapelmaster": "ミュージシャン",
    "Kirchenmusikdirektor": "ミュージシャン",

    # ── 医療・医学 ────────────────────────────────────────────────────
    "physician": "医師",
    "surgeon": "外科医",
    "psychiatrist": "カウンセラー・心理士",
    "psychologist": "カウンセラー・心理士",
    "neurologist": "医師",
    "anatomist": "医師",
    "physiologist": "医師",
    "pathologist": "医師",
    "ophthalmologist": "医師",
    "gynecologist": "外科医",
    "obstetrician": "外科医",
    "dermatologist": "医師",
    "orthopedic surgeon": "外科医",
    "otolaryngologist": "医師",
    "otologist": "医師",
    "pediatrician": "医師",
    "pharmacologist": "薬剤師",
    "pharmacist": "薬剤師",
    "microbiologist": "研究者（独立系）",
    "bacteriologist": "研究者（独立系）",
    "virologist": "研究者（独立系）",
    "biologist": "研究者（独立系）",
    "biophysicist": "研究者（独立系）",
    "medical researcher": "研究者（独立系）",
    "military physician": "医師",
    "naval surgeon": "外科医",
    "general practitioner": "医師",
    "internist": "医師",
    "medic": "医師",
    "physician writer": "医師",
    "nurse": "看護師",
    "hygienist": "医師",
    "veterinarian": "医師",
    "veterinary scientist": "研究者（独立系）",
    "dentist": "医師",
    "homeopath": "セラピスト",
    "balneologist": "医師",
    "toxicologist": "研究者（独立系）",
    "parasitologist": "研究者（独立系）",
    "helminthologist": "研究者（独立系）",
    "oncologist": "医師",
    "histologist": "研究者（独立系）",
    "embryologist": "研究者（独立系）",
    "emergency medical technician": "医師",
    "urologist": "外科医",
    "medical historian": "研究者（独立系）",
    "medical writer": "作家",
    "parapsychologist": "占い師・スピリチュアル",

    # ── 自然科学・研究 ────────────────────────────────────────────────
    "scientist": "研究者（独立系）",
    "physicist": "研究者（独立系）",
    "chemist": "研究者（独立系）",
    "mathematician": "研究者（独立系）",
    "astronomer": "研究者（独立系）",
    "botanist": "研究者（独立系）",
    "zoologist": "研究者（独立系）",
    "geologist": "研究者（独立系）",
    "naturalist": "研究者（独立系）",
    "entomologist": "研究者（独立系）",
    "mineralogist": "研究者（独立系）",
    "ornithologist": "研究者（独立系）",
    "paleontologist": "研究者（独立系）",
    "archaeologist": "研究者（独立系）",
    "anthropologist": "研究者（独立系）",
    "ethnologist": "研究者（独立系）",
    "ethnographer": "研究者（独立系）",
    "sociologist": "研究者（独立系）",
    "political scientist": "研究者（独立系）",
    "economist": "研究者（独立系）",
    "statistical collector": "研究者（独立系）",
    "statistician": "研究者（独立系）",
    "geographer": "研究者（独立系）",
    "meteorologist": "研究者（独立系）",
    "seismologist": "研究者（独立系）",
    "volcanologist": "研究者（独立系）",
    "geodesist": "研究者（独立系）",
    "hydrographer": "研究者（独立系）",
    "cartographer": "研究者（独立系）",
    "mycologist": "研究者（独立系）",
    "malacologist": "研究者（独立系）",
    "ichthyologist": "研究者（独立系）",
    "lepidopterist": "研究者（独立系）",
    "carcinologist": "研究者（独立系）",
    "conchologist": "研究者（独立系）",
    "lichenologist": "研究者（独立系）",
    "phycologist": "研究者（独立系）",
    "bryologist": "研究者（独立系）",
    "agrostologist": "研究者（独立系）",
    "pomologist": "研究者（独立系）",
    "coleopterist": "研究者（独立系）",
    "hymenopterist": "研究者（独立系）",
    "myriapodologist": "研究者（独立系）",
    "paleobotanist": "研究者（独立系）",
    "crystallographer": "研究者（独立系）",
    "stratigrapher": "研究者（独立系）",
    "invertebrate paleontologist": "研究者（独立系）",
    "petrologist": "研究者（独立系）",
    "speleologist": "研究者（独立系）",
    "ecologist": "研究者（独立系）",
    "earth scientist": "研究者（独立系）",
    "geophysicist": "研究者（独立系）",
    "telmatologist": "研究者（独立系）",
    "herpetologist": "研究者（独立系）",
    "microscopist": "研究者（独立系）",
    "genetic researcher": "研究者（独立系）",
    "geneticist": "研究者（独立系）",
    "researcher": "研究者（独立系）",
    "scientific collector": "研究者（独立系）",
    "botanical collector": "研究者（独立系）",
    "zoological collector": "研究者（独立系）",
    "taxidermist": "研究者（独立系）",
    "preparator": "研究者（独立系）",
    "academic": "研究者（独立系）",
    "scholar": "研究者（独立系）",
    "polymath": "研究者（独立系）",
    "intellectual": "哲学者・思想家",
    "prehistorian": "研究者（独立系）",
    "classical archaeologist": "研究者（独立系）",
    "assyriologist": "研究者（独立系）",
    "egyptologist": "研究者（独立系）",
    "sinologist": "研究者（独立系）",
    "japanologist": "研究者（独立系）",
    "Indologist": "研究者（独立系）",
    "arabist": "研究者（独立系）",
    "orientalist": "研究者（独立系）",
    "Islamicist": "研究者（独立系）",
    "coptologist": "研究者（独立系）",
    "bohemicist": "研究者（独立系）",
    "hispanist": "研究者（独立系）",
    "slavist": "研究者（独立系）",
    "germanist": "研究者（独立系）",
    "romanist": "研究者（独立系）",
    "latinist": "研究者（独立系）",
    "medievalist": "研究者（独立系）",
    "Cellar Master": "研究者（独立系）",
    "historian of mathematics": "研究者（独立系）",
    "sport historian": "研究者（独立系）",
    "regional historian": "研究者（独立系）",
    "local historian": "研究者（独立系）",
    "literary historian": "研究者（独立系）",
    "art historian": "研究者（独立系）",
    "military historian": "研究者（独立系）",
    "economic historian": "研究者（独立系）",
    "social historian": "研究者（独立系）",
    "church historian": "研究者（独立系）",
    "legal historian": "研究者（独立系）",
    "historian of religion": "研究者（独立系）",
    "humanities scholar": "研究者（独立系）",
    "forestry scientist": "研究者（独立系）",
    "agricultural chemist": "研究者（独立系）",
    "architectural historian": "研究者（独立系）",

    # ── 人文・哲学・思想 ──────────────────────────────────────────────
    "historian": "研究者（独立系）",
    "philosopher": "哲学者・思想家",
    "theologian": "哲学者・思想家",
    "Catholic theologian": "哲学者・思想家",
    "Protestant theologian": "哲学者・思想家",
    "Orthodox theologian": "哲学者・思想家",
    "biblical scholar": "哲学者・思想家",
    "Hebrew Bible scholar": "哲学者・思想家",
    "Judaic scholar": "哲学者・思想家",
    "religious studies scholar": "哲学者・思想家",
    "literary theorist": "哲学者・思想家",
    "art theorist": "哲学者・思想家",
    "music theorist": "哲学者・思想家",
    "ethicist": "哲学者・思想家",
    "aesthetician": "哲学者・思想家",
    "political economist": "研究者（独立系）",
    "eugenicist": "研究者（独立系）",
    "racial theorist": "哲学者・思想家",
    "encyclopedist": "作家",
    "encyclopédistes": "作家",
    "mystic": "占い師・スピリチュアル",
    "astrologer": "占い師・スピリチュアル",
    "spiritual medium": "占い師・スピリチュアル",

    # ── 文学・著述 ────────────────────────────────────────────────────
    "writer": "作家",
    "author": "作家",
    "novelist": "作家",
    "poet": "作家",
    "playwright": "作家",
    "essayist": "作家",
    "biographer": "作家",
    "prose writer": "作家",
    "non-fiction writer": "作家",
    "science fiction writer": "作家",
    "children's writer": "作家",
    "short story writer": "作家",
    "travel writer": "作家",
    "diarist": "作家",
    "autobiographer": "作家",
    "librettist": "作家",
    "hymnwriter": "作家",
    "literary critic": "批評家・評論家",
    "literary scholar": "研究者（独立系）",
    "dialect writer": "作家",
    "regional writer": "作家",
    "church writer": "作家",
    "religious writer": "作家",
    "medical writer": "作家",
    "military writer": "作家",
    "comedy writer": "作家",
    "textbook writer": "作家",
    "comics writer": "作家",
    "screenwriter": "作家",
    "lyricist": "ミュージシャン",
    "songwriter": "ミュージシャン",
    "singer-songwriter": "ミュージシャン",
    "homme de lettres": "作家",
    "man of letters": "作家",
    "dictionary author": "作家",
    "lexicographer": "作家",
    "folklorist": "研究者（独立系）",
    "oral tradition collector": "研究者（独立系）",
    "mythographer": "作家",
    "humorist": "作家",
    "publicist": "批評家・評論家",
    "columnist": "批評家・評論家",
    "critic": "批評家・評論家",
    "music critic": "批評家・評論家",
    "art critic": "批評家・評論家",
    "literary editor": "出版・編集者",
    "journal editor": "出版・編集者",
    "magazine editor": "出版・編集者",
    "orator": "批評家・評論家",

    # ── ジャーナリズム・出版 ──────────────────────────────────────────
    "journalist": "批評家・評論家",
    "opinion journalist": "批評家・評論家",
    "editor": "出版・編集者",
    "editor-in-chief": "出版・編集者",
    "newspaper editor": "出版・編集者",
    "editing staff": "出版・編集者",
    "publisher": "出版・編集者",
    "bookseller": "出版・編集者",
    "music publisher": "出版・編集者",
    "newspaper proprietor": "経営者",
    "translator": "出版・編集者",
    "literary translator": "出版・編集者",
    "Bible translator": "出版・編集者",
    "bibliographer": "出版・編集者",
    "philologist": "研究者（独立系）",
    "classical philologist": "研究者（独立系）",
    "classical scholar": "研究者（独立系）",
    "linguist": "研究者（独立系）",
    "musicologist": "研究者（独立系）",
    "musicographer": "研究者（独立系）",
    "palaeographer": "研究者（独立系）",
    "numismatist": "研究者（独立系）",
    "philatelist": "研究者（独立系）",
    "heraldist": "研究者（独立系）",
    "genealogist": "研究者（独立系）",
    "foreign correspondent": "批評家・評論家",
    "sports journalist": "批評家・評論家",
    "economic journalist": "批評家・評論家",
    "music journalist": "批評家・評論家",
    "theatre critic": "批評家・評論家",
    "photojournalist": "カメラマン",
    "printer": "出版・編集者",
    "typographer": "出版・編集者",
    "typesetter": "出版・編集者",
    "book printer": "出版・編集者",
    "bookbinder": "職人",
    "chroniqueur": "批評家・評論家",
    "editorial cartoonist": "アーティスト",
    "caricaturist": "アーティスト",
    "cartoonist": "アーティスト",

    # ── 美術・造形 ────────────────────────────────────────────────────
    "painter": "アーティスト",
    "sculptor": "アーティスト",
    "illustrator": "アーティスト",
    "photographer": "カメラマン",
    "printmaker": "アーティスト",
    "engraver": "アーティスト",
    "etcher": "アーティスト",
    "lithographer": "アーティスト",
    "xylographer": "アーティスト",
    "graphic artist": "アーティスト",
    "visual artist": "アーティスト",
    "artist": "アーティスト",
    "watercolorist": "アーティスト",
    "portrait painter": "アーティスト",
    "landscape painter": "アーティスト",
    "genre painter": "アーティスト",
    "history painter": "アーティスト",
    "decorative painter": "アーティスト",
    "miniature painter": "アーティスト",
    "animal painter": "アーティスト",
    "flower painter": "アーティスト",
    "fresco painter": "アーティスト",
    "pastellist": "アーティスト",
    "draftsperson": "アーティスト",
    "scientific illustrator": "アーティスト",
    "botanical illustrator": "アーティスト",
    "architectural draftsperson": "アーティスト",
    "graphic designer": "デザイナー",
    "designer": "デザイナー",
    "interior designer": "デザイナー",
    "fashion designer": "デザイナー",
    "fashion illustrator": "デザイナー",
    "jewelry designer": "デザイナー",
    "costume designer": "デザイナー",
    "scenographer": "デザイナー",
    "stained-glass artist": "アーティスト",
    "glass artist": "アーティスト",
    "ceramicist": "アーティスト",
    "mosaicist": "アーティスト",
    "copper engraver": "アーティスト",
    "wood engraver": "アーティスト",
    "wood carver": "職人",
    "exlibrist": "アーティスト",
    "folk artist": "アーティスト",
    "art dealer": "経営者",
    "art collector": "経営者",
    "patron of the arts": "経営者",
    "curator": "図書館員",
    "exhibition curator": "図書館員",
    "museum professional": "図書館員",
    "museologist": "研究者（独立系）",
    "museum registrar": "図書館員",
    "conservator": "図書館員",
    "restorer": "職人",
    "colorist": "アーティスト",
    "panoramist": "アーティスト",
    "type designer": "デザイナー",

    # ── 音楽 ──────────────────────────────────────────────────────────
    "composer": "ミュージシャン",
    "conductor": "ミュージシャン",
    "musician": "ミュージシャン",
    "pianist": "ミュージシャン",
    "organist": "ミュージシャン",
    "violinist": "ミュージシャン",
    "cellist": "ミュージシャン",
    "violist": "ミュージシャン",
    "double-bassist": "ミュージシャン",
    "harpist": "ミュージシャン",
    "trumpeter": "ミュージシャン",
    "horn player": "ミュージシャン",
    "bassoonist": "ミュージシャン",
    "singer": "ミュージシャン",
    "opera singer": "ミュージシャン",
    "operetta singer": "ミュージシャン",
    "traditional folk singer": "ミュージシャン",
    "folk musician": "ミュージシャン",
    "classical composer": "ミュージシャン",
    "church musician": "ミュージシャン",
    "music arranger": "ミュージシャン",
    "opera vocal coach": "ミュージシャン",
    "opera director": "ミュージシャン",
    "concertmaster": "ミュージシャン",
    "chansonnier": "ミュージシャン",
    "cantor": "ミュージシャン",
    "hazzan": "ミュージシャン",
    "succentor": "ミュージシャン",
    "luthier": "職人",
    "organ builder": "職人",
    "musical instrument maker": "職人",
    "harmonium builder": "職人",
    "piano maker": "職人",
    "music dealer": "経営者",
    "music publicist": "プロモーター",
    "music director": "ミュージシャン",
    "chef de chant": "ミュージシャン",

    # ── 演劇・映像・芸能 ──────────────────────────────────────────────
    "actor": "芸能・タレント",
    "stage actor": "芸能・タレント",
    "film actor": "芸能・タレント",
    "kabuki actor": "芸能・タレント",
    "dancer": "芸能・タレント",
    "ballet dancer": "芸能・タレント",
    "comedian": "芸能・タレント",
    "entertainer": "芸能・タレント",
    "magician": "芸能・タレント",
    "circus performer": "芸能・タレント",
    "sideshow performer": "芸能・タレント",
    "clown": "芸能・タレント",
    "showman": "芸能・タレント",
    "film director": "イベントプロデューサー",
    "theatrical director": "イベントプロデューサー",
    "theatre manager": "イベントプロデューサー",
    "film producer": "イベントプロデューサー",
    "impresario": "イベントプロデューサー",
    "circus director": "イベントプロデューサー",
    "theatrical producer": "イベントプロデューサー",
    "filmmaker": "イベントプロデューサー",
    "dramaturge": "作家",
    "choreographer": "アーティスト",

    # ── 建築・工学 ────────────────────────────────────────────────────
    "architect": "建築士",
    "landscape architect": "建築士",
    "civil engineer": "エンジニア（新領域）",
    "engineer": "エンジニア（新領域）",
    "mechanical engineer": "エンジニア（新領域）",
    "electrical engineer": "エンジニア（新領域）",
    "railway engineer": "エンジニア（新領域）",
    "mining engineer": "エンジニア（新領域）",
    "hydraulic engineer": "エンジニア（新領域）",
    "military engineer": "エンジニア（新領域）",
    "marine architect": "建築士",
    "metallurgist": "エンジニア（新領域）",
    "metallurgical engineer": "エンジニア（新領域）",
    "agricultural engineer": "エンジニア（新領域）",
    "design engineer": "エンジニア（新領域）",
    "bridge engineer": "エンジニア（新領域）",
    "locomotive designer": "発明家",
    "engineer of the French Corps of Bridges and Roads": "エンジニア（新領域）",
    "surveyor": "エンジニア（新領域）",
    "urban planner": "建築士",
    "master builder": "建築士",
    "general contractor": "建築士",
    "building contractor": "建築士",
    "state-certified engineers specializing in building construction": "建築士",
    "technician": "エンジニア（新領域）",
    "mechanical technician": "エンジニア（新領域）",
    "military flight engineer": "エンジニア（新領域）",
    "instrument maker": "職人",
    "inventor": "発明家",

    # ── 経営・実業・金融 ──────────────────────────────────────────────
    "businessperson": "経営者",
    "entrepreneur": "起業家",
    "industrialist": "経営者",
    "banker": "銀行員",
    "merchant": "商社マン",
    "stockbroker": "投資家",
    "investor": "投資家",
    "financier": "投資家",
    "investment banker": "投資家",
    "capitalist": "投資家",
    "manufacturer": "経営者",
    "factory owner": "経営者",
    "ship-owner": "経営者",
    "railway executive": "大企業管理職",
    "hotel manager": "経営者",
    "hotel owner": "経営者",
    "land owner": "経営者",
    "large estate owner": "経営者",
    "estate owner": "経営者",
    "business magnate": "経営者",
    "agricultural entrepreneur": "起業家",
    "wholesale merchant": "商社マン",
    "wholesaler": "商社マン",
    "timber merchant": "商社マン",
    "wine merchant": "商社マン",
    "bookseller": "出版・編集者",
    "shopkeeper": "個人事業主",
    "shop assistant": "営業",
    "auctioneer": "営業",
    "salesperson": "営業",
    "retail worker": "営業",
    "art dealer": "経営者",
    "real-estate agent": "不動産",
    "land agent": "不動産",
    "stock and station agent": "営業",
    "bank manager": "銀行員",
    "accountant": "会計士・税理士",
    "senior accountant": "会計士・税理士",
    "bookkeeper": "経理・財務",
    "insurance broker": "経理・財務",
    "nightclub owner": "経営者",
    "café owner": "料理人・シェフ",
    "brewer": "経営者",
    "brewmaster": "職人",
    "distiller": "職人",
    "chocolatier": "職人",
    "grocer": "個人事業主",
    "ironmaster": "経営者",
    "shipbuilder": "エンジニア（新領域）",

    # ── 軍事 ──────────────────────────────────────────────────────────
    "military personnel": "警察・消防・自衛隊",
    "military officer": "警察・消防・自衛隊",
    "soldier": "警察・消防・自衛隊",
    "naval officer": "警察・消防・自衛隊",
    "army officer": "警察・消防・自衛隊",
    "naval personnel": "警察・消防・自衛隊",
    "military leader": "警察・消防・自衛隊",
    "military commander": "警察・消防・自衛隊",
    "military historian": "研究者（独立系）",
    "admiral": "警察・消防・自衛隊",
    "artillerist": "警察・消防・自衛隊",
    "cavalry master": "警察・消防・自衛隊",
    "resistance fighter": "警察・消防・自衛隊",
    "military musician": "ミュージシャン",
    "military chaplain": "官僚・行政",
    "submariner": "警察・消防・自衛隊",
    "army scout": "警察・消防・自衛隊",
    "spy": "警察・消防・自衛隊",
    "samurai": "警察・消防・自衛隊",
    "bushi": "警察・消防・自衛隊",
    "police officer": "警察・消防・自衛隊",
    "police constable": "警察・消防・自衛隊",
    "chief of police": "警察・消防・自衛隊",
    "peace officer": "警察・消防・自衛隊",
    "firefighter": "警察・消防・自衛隊",
    "sheriff": "警察・消防・自衛隊",
    "town marshal": "警察・消防・自衛隊",
    "Marineoffizier": "警察・消防・自衛隊",
    "special constable": "警察・消防・自衛隊",

    # ── 宗教 ──────────────────────────────────────────────────────────
    "Catholic priest": "教師・教授",
    "priest": "教師・教授",
    "Catholic bishop": "教師・教授",
    "curate": "教師・教授",
    "pastor": "教師・教授",
    "missionary": "教師・教授",
    "Catholic missionary": "教師・教授",
    "Anglican priest": "教師・教授",
    "rabbi": "教師・教授",
    "coadjutor": "教師・教授",
    "Eastern Orthodox priest": "教師・教授",
    "monk": "教師・教授",
    "nun": "教師・教授",
    "Christian nun": "教師・教授",
    "cleric": "教師・教授",
    "preacher": "教師・教授",
    "friar": "教師・教授",
    "deacon": "教師・教授",
    "Catholic deacon": "教師・教授",
    "vicar": "教師・教授",
    "canon": "教師・教授",
    "chaplain": "教師・教授",
    "parson": "教師・教授",
    "presbyter": "教師・教授",
    "theologian": "哲学者・思想家",
    "clergyman": "教師・教授",
    "vicar general": "教師・教授",
    "provost": "官僚・行政",
    "prelate": "教師・教授",
    "spiritual director": "セラピスト",
    "almoner": "社会福祉士",
    "Christian minister": "教師・教授",
    "Lutheran pastor": "教師・教授",
    "Reformed pastor": "教師・教授",
    "assistant pastor": "教師・教授",
    "Greek-Catholic priest": "教師・教授",
    "hegumen": "教師・教授",
    "Latin Catholic priest": "教師・教授",
    "religious leader": "教師・教授",
    "religious figure": "教師・教授",
    "religious": "教師・教授",
    "daimyo": "政治家",
    "ulema": "哲学者・思想家",
    "muhaddith": "哲学者・思想家",
    "evangelist": "教師・教授",
    "Reverend": "教師・教授",
    "Father": "教師・教授",
    "Buddhist monk": "教師・教授",
    "Orthodox theologian": "哲学者・思想家",
    "temperance worker": "社会福祉士",

    # ── 図書館・文書 ──────────────────────────────────────────────────
    "librarian": "図書館員",
    "archivist": "図書館員",
    "bibliophile": "図書館員",
    "antiquarian": "図書館員",
    "collector": "研究者（独立系）",

    # ── 社会福祉・慈善 ────────────────────────────────────────────────
    "philanthropist": "社会福祉士",
    "humanitarian": "社会福祉士",
    "charity worker": "社会福祉士",
    "benefactor": "社会福祉士",
    "donor": "社会福祉士",
    "community leader": "社会福祉士",
    "cultural worker": "社会福祉士",

    # ── 農業・自然 ────────────────────────────────────────────────────
    "farmer": "個人事業主",
    "agronomist": "研究者（独立系）",
    "botanist": "研究者（独立系）",
    "horticulturist": "個人事業主",
    "gardener": "個人事業主",
    "forester": "個人事業主",
    "winegrower": "個人事業主",
    "cattle rancher": "個人事業主",
    "pastoralist": "個人事業主",
    "fruit grower": "個人事業主",
    "coffee grower": "個人事業主",
    "nursery gardener": "個人事業主",
    "beekeeper": "個人事業主",
    "dog breeder": "個人事業主",
    "aquarist": "研究者（独立系）",
    "pomologist": "研究者（独立系）",
    "conservationist": "社会福祉士",
    "environmentalist": "社会福祉士",

    # ── スポーツ ──────────────────────────────────────────────────────
    "athlete": "アスリート",
    "cricketer": "アスリート",
    "baseball player": "アスリート",
    "association football player": "アスリート",
    "rugby union player": "アスリート",
    "tennis player": "アスリート",
    "chess player": "アスリート",
    "gymnast": "アスリート",
    "rower": "アスリート",
    "swimmer": "アスリート",
    "mountaineer": "アスリート",
    "equestrian": "アスリート",
    "golfer": "アスリート",
    "polo player": "アスリート",
    "archer": "アスリート",
    "jockey": "アスリート",
    "ballet dancer": "芸能・タレント",
    "ice hockey player": "アスリート",
    "rugby union match official": "アスリート",
    "association football referee": "アスリート",
    "cricket umpire": "アスリート",
    "Australian rules football player": "アスリート",
    "rugby league player": "アスリート",
    "competitive diver": "アスリート",
    "sport shooter": "アスリート",
    "racing automobile driver": "アスリート",
    "adventurer": "アスリート",
    "explorer": "アスリート",
    "polar explorer": "アスリート",
    "scientific explorer": "研究者（独立系）",
    "traveler": "アスリート",
    "world traveler": "アスリート",
    "trekker": "アスリート",
    "mountaineer": "アスリート",
    "mountain guide": "アスリート",
    "balloonist": "アスリート",
    "sailor": "警察・消防・自衛隊",
    "ship captain": "経営者",
    "skipper": "経営者",
    "navigator": "警察・消防・自衛隊",
    "maritime pilot": "経営者",

    # ── 職人・技術 ────────────────────────────────────────────────────
    "goldsmith": "職人",
    "watchmaker": "職人",
    "cabinetmaker": "職人",
    "furniture maker": "職人",
    "joiner": "職人",
    "carpenter": "職人",
    "stonemason": "職人",
    "bricklayer": "職人",
    "blacksmith": "職人",
    "artistic blacksmith": "職人",
    "locksmith": "職人",
    "tinsmith": "職人",
    "tailor": "職人",
    "dressmaker": "職人",
    "weaver": "職人",
    "bobbin lace maker": "職人",
    "embroiderer": "職人",
    "cobbler": "職人",
    "machinist": "職人",
    "mechanic": "職人",
    "electrician": "エンジニア（新領域）",
    "fitter": "職人",
    "miller": "職人",
    "sawmiller": "職人",
    "potter": "職人",
    "ceramicist": "アーティスト",

    # ── その他・分類困難 ──────────────────────────────────────────────
    "aristocrat": "政治家",
    "monarch": "政治家",
    "socialite": "芸能・タレント",
    "salonnière": "芸能・タレント",
    "lady-in-waiting": "官僚・行政",
    "courtier": "官僚・行政",
    "medalist": "アスリート",
    "Esperantist": "研究者（独立系）",
    "settler": "個人事業主",
    "laborer": "個人事業主",
    "coal miner": "個人事業主",
    "miner": "個人事業主",
    "railway worker": "エンジニア（新領域）",
    "railwayman": "エンジニア（新領域）",
    "telegraphist": "エンジニア（新領域）",
    "station master": "管理職",
    "train driver": "エンジニア（新領域）",
    "bartender": "料理人・シェフ",
    "cook": "料理人・シェフ",
    "confectioner": "料理人・シェフ",
    "oenologist": "研究者（独立系）",
    "innkeeper": "経営者",
    "clerk": "管理職",
    "Esperantist": "研究者（独立系）",
    "man of letters": "作家",
    "homme de lettres": "作家",
    "propaganda": "政治家",
    "resistance fighter": "警察・消防・自衛隊",
    "folk artist": "アーティスト",
    "traditional leader or chief": "政治家",
    "consultant": "経営者",
    "Warden": "官僚・行政",
    "proctor": "官僚・行政",
    "bursar": "経理・財務",
    "Hofmeister": "官僚・行政",
    "Privatier": "投資家",
    "privatier": "投資家",
    "shipping magnate": "経営者",
    "expeditor": "商社マン",
    "factor": "商社マン",
    "trader": "商社マン",
    "insect dealer": "商社マン",
    "trader of naturalia": "商社マン",
    "teamster": "個人事業主",
    "postal worker": "官僚・行政",
    "yeoman": "個人事業主",
    "cowboy": "個人事業主",
    "fisher": "個人事業主",
    "pigeon fancier": "個人事業主",
    "life guard": "警察・消防・自衛隊",
    "lifeguard": "警察・消防・自衛隊",
    "huntsman": "個人事業主",
    "hunter": "個人事業主",
    "big game hunter": "個人事業主",
    "demi-mondaine": "芸能・タレント",
    "public figure": "芸能・タレント",
    "sports official": "管理職",
    "association football executive": "経営者",
    "film exhibitor": "経営者",
    "film distributor": "経営者",
    "chilcare provider": "保育士",
    "childcare provider": "保育士",
    "director of nursing": "看護師",
    "housewife": "個人事業主",
    "club woman": "個人事業主",
    "clubwoman": "個人事業主",
    "benefactor": "社会福祉士",
    "swordfighter": "アスリート",
    "portrait photographer": "カメラマン",
    "man of letters": "作家",
    "furrier": "職人",
    "hatter": "職人",
    "ironmonger": "職人",
    "canut": "職人",
    "pecks": "職人",
    "stationer": "個人事業主",
    "bibliophile": "図書館員",
    "animalier": "アーティスト",
    "rider": "アスリート",
    "medalist": "アスリート",
    "photojournalist": "カメラマン",
    "prosecutor": "裁判官・弁護士",
    "prosecuting attorney": "裁判官・弁護士",
    "pedagogue": "教師・教授",
    "choirmaster": "ミュージシャン",
    "Sokol": "アスリート",
    "rikishi": "アスリート",
    "pyrotechnist": "職人",
    "mosaicist": "アーティスト",
    "hydrographer": "研究者（独立系）",
    "geophysicist": "研究者（独立系）",
    "earth scientist": "研究者（独立系）",
    "campanologist": "職人",
    "saddler": "職人",
    "printer to the King": "出版・編集者",
    "volapükist": "研究者（独立系）",
    "societe": "経営者",
    "sanitary inspector": "官僚・行政",
    "environmental health officer": "官僚・行政",
    "procurer": "管理職",
    "stamper": "職人",
    "stamp forger": "職人",
    "optician": "職人",
    "chimney sweep": "職人",
    "criminal": "個人事業主",
    "gangster": "個人事業主",
    "robber": "個人事業主",
    "serial killer": "個人事業主",
    "terrorist": "個人事業主",
    "folklore collector": "研究者（独立系）",
    "Esperantist": "研究者（独立系）",
    "embetsperson": "官僚・行政",
    "assistant": "管理職",
    "employee": "管理職",
    "forester": "個人事業主",
    "grand couturier": "デザイナー",
    "draftsperson": "アーティスト",
    "prosecutor": "裁判官・弁護士",
    "boatman": "個人事業主",
    "procurer": "管理職",
    "Indiano": "経営者",
    "intellectual": "哲学者・思想家",
    "conservationist": "社会福祉士",
    "preservationist": "社会福祉士",
    "historic preservationist": "社会福祉士",
    "music writer": "作家",
    "music arranger": "ミュージシャン",
    "memoir editor": "出版・編集者",
    "comedy writer": "作家",
    "comics writer": "作家",
    "diary writer": "作家",
    "sex reformer": "社会福祉士",
    "eugenicist": "研究者（独立系）",
    "racial theorist": "哲学者・思想家",
    "badminton executive and administrator": "管理職",
    "hospital chief executive officer": "経営者",
    "managing director": "経営者",
    "deputy general director": "経営者",
    "manufacturing manager": "管理職",
    "community leader": "社会福祉士",
    "school superintendent": "教師・教授",
    "Theaterintendant": "イベントプロデューサー",
    "Präses": "教師・教授",
    "Dutch East India Company": "商社マン",
    "Chamberlain of Japan": "官僚・行政",
    "Registrar of the House of Representatives": "官僚・行政",
    "Minister–Secretary of State for Finland": "政治家",
    "mayor of Odesa": "政治家",
    "Huissier de justice": "裁判官・弁護士",
    "bedel": "官僚・行政",
    "prospector": "個人事業主",
    "mycologist": "研究者（独立系）",
    "telmatologist": "研究者（独立系）",
    "suffragist": "政治家",
    "suffragette": "政治家",
    "mountaineer": "アスリート",
    "chroniqueur": "批評家・評論家",
    "doctor": "医師",
    "medic": "医師",
    "general practitioner": "医師",
    "chronicler": "作家",
    "singer-songwriter": "ミュージシャン",
    "song writer": "ミュージシャン",
    "Clerical Officer": "官僚・行政",
    "pigeon fancier": "個人事業主",
    "director of land survey": "官僚・行政",
    "Sokol": "アスリート",
    "balloon": "アスリート",
    "chess master": "アスリート",
    "huntsman": "個人事業主",
    "Polish nobility": "政治家",
    "łowczy": "個人事業主",
    "łowczy": "個人事業主",
    "embetsperson": "官僚・行政",
    "shogunate retainer": "警察・消防・自衛隊",
    "pedagog": "教師・教授",
    "pedagogue": "教師・教授",
    "pirate": "個人事業主",
    "warlord": "警察・消防・自衛隊",
    "art director": "デザイナー",
    "public administration of France": "官僚・行政",
    "Privatdozent": "教師・教授",
    "Oberlehrer": "教師・教授",
    "Beamter": "官僚・行政",
    "Landrat": "官僚・行政",
    "Oberamtmann": "官僚・行政",
    "Schulrat": "官僚・行政",
    "Ministerialrat": "官僚・行政",
    "Amtmann": "官僚・行政",
    "Hofmeister": "官僚・行政",
    "jeweler": "職人",
    "lord of the manor": "経営者",
    "possessor": "経営者",
    "founder": "起業家",
    "schoolmaster": "教師・教授",
    "peasant": "個人事業主",
    "lecturer": "教師・教授",
}
